js_path /var/www/crc;
js_import og from og.js;

server {
        root /var/www/crc;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name hesabkesh.ir;

        charset utf-8;
        gzip on;
        gzip_types text/css application/javascript image/svg+xml application/xml text/plain;

        location = /index.html {
                return 301 /$is_args$args;
        }

        location = / {
                js_content og.page;
        }

        location / {
                try_files $uri @page;
        }

        location @page {
                js_content og.page;
        }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hesabkesh.ir/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hesabkesh.ir/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    if ($host = hesabkesh.ir) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



        server_name hesabkesh.ir;
    listen 80;
    return 404; # managed by Certbot


}
